// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI78ZDxgjS711Gxsv1WGstsoFyUNJILMU',
    appId: '1:520655900028:android:e67103d011738dcfc428f9',
    messagingSenderId: '520655900028',
    projectId: 'kanagawaku-machizukan-dev',
    storageBucket: 'kanagawaku-machizukan-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3nG-tT0WFuAD9pXX0myTuOJbapghIx8',
    appId: '1:520655900028:ios:9c7386b76a12fc68c428f9',
    messagingSenderId: '520655900028',
    projectId: 'kanagawaku-machizukan-dev',
    storageBucket: 'kanagawaku-machizukan-dev.firebasestorage.app',
    androidClientId: '520655900028-8uamimv06uci32c44utop9sameqgtald.apps.googleusercontent.com',
    iosClientId: '520655900028-nogk81g4o1rnrorp70a62m3h43cc3l3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}